# Generated by Django 5.1.15 on 2026-05-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('dividend_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual'), ('IRREGULAR', 'Irregular')], default='QUARTERLY', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='tracker.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=4, max_digits=14)),
                ('average_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='tracker.ticker')),
            ],
            options={
                'ordering': ['ticker__symbol'],
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('amount_per_share', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(choices=[('YFINANCE', 'yfinance'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='tracker.ticker')),
            ],
            options={
                'ordering': ['-ex_date'],
                'unique_together': {('ticker', 'ex_date')},
            },
        ),
    ]
